"""
Django settings for flyingfox project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_z__7v1ikw!pdsk5x$$d!t&l*egm)m4f^u5&@kwb$5ak2a0=qi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get(
    "DEBUG",
    "False"
).lower() == "true"

# DEBUG=True


ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "flyingfoxadventuremunnar.com",
    "www.flyingfoxadventuremunnar.com",
    "flying-fox.onrender.com",
    "*"
]

RENDER_EXTERNAL_HOSTNAME = os.environ.get(
    "RENDER_EXTERNAL_HOSTNAME"
)

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "https://flyingfoxadventuremunnar.com",
    "https://www.flyingfoxadventuremunnar.com",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'storages',

    "flyingfox_app",
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
     'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flyingfox.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                "flyingfox_app.context_processors.footer_popular_rides",
            ],
        },
    },
]

WSGI_APPLICATION = 'flyingfox.wsgi.application'

WHITENOISE_MANIFEST_STRICT = False


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=60,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# ==========================================
# STATIC FILES
# ==========================================

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"



# ==========================================
# MEDIA FILES
# ==========================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# STORAGES = {
#     "default": {
#         "BACKEND": "django.core.files.storage.FileSystemStorage",
#     },
#     "staticfiles": {
#         "BACKEND": (
#             "whitenoise.storage."
#             "CompressedManifestStaticFilesStorage"
#         ),
#     },
# }

import os

# ==========================================
# MEDIA FILES - SUPABASE S3
# ==========================================


# ==========================================
# SUPABASE STORAGE
# ==========================================

SUPABASE_S3_ENDPOINT = os.environ.get(
    "SUPABASE_S3_ENDPOINT"
)

SUPABASE_S3_REGION = os.environ.get(
    "SUPABASE_S3_REGION",
    "ap-south-1",
)

SUPABASE_S3_ACCESS_KEY_ID = os.environ.get(
    "SUPABASE_S3_ACCESS_KEY_ID"
)

SUPABASE_S3_SECRET_ACCESS_KEY = os.environ.get(
    "SUPABASE_S3_SECRET_ACCESS_KEY"
)


STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",

        "OPTIONS": {
            "access_key":
                SUPABASE_S3_ACCESS_KEY_ID,

            "secret_key":
                SUPABASE_S3_SECRET_ACCESS_KEY,

            "bucket_name":
                "media",

            "endpoint_url":
                SUPABASE_S3_ENDPOINT,

            "region_name":
                SUPABASE_S3_REGION,

            "addressing_style":
                "path",

            "signature_version":
                "s3v4",

            "querystring_auth":
                False,

            "file_overwrite":
                False,

            # IMPORTANT:
            # Browser-facing Supabase public URL
            "custom_domain":
                "yiprdoylivpttwfjqezl.storage.supabase.co"
                "/storage/v1/object/public/media",
        },
    },

    "staticfiles": {
        "BACKEND":
            "whitenoise.storage."
            "CompressedStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



import os


# ==========================================
# EMAIL SETTINGS
# ==========================================

EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
)

EMAIL_HOST = "smtp.zoho.in"

EMAIL_PORT = 587

EMAIL_USE_TLS = True

# EMAIL_HOST_USER = "booking@flyingfoxadventuremunnar.com"
# EMAIL_HOST_PASSWORD ="RKX0NdqeudAL"
# DEFAULT_FROM_EMAIL = "booking@flyingfoxadventuremunnar.com"
# CONTACT_RECEIVER_EMAIL ="booking@flyingfoxadventuremunnar.com"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.environ.get(
    "EMAIL_HOST",
    "smtp.zoho.in"
)

EMAIL_PORT = int(
    os.environ.get("EMAIL_PORT", "587")
)

EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.environ.get(
    "EMAIL_HOST_USER",
    ""
)

EMAIL_HOST_PASSWORD = os.environ.get(
    "EMAIL_HOST_PASSWORD",
    ""
)

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER,
)

CONTACT_RECEIVER_EMAIL = os.environ.get(
    "CONTACT_RECEIVER_EMAIL",
    EMAIL_HOST_USER,
)

EMAIL_TIMEOUT = 30


# ==========================================
# whatsapp SETTINGS
# ==========================================
TWILIO_WHATSAPP_FROM = "whatsapp:+17372508034"

TWILIO_WHATSAPP_CONTENT_SID = (
    "HXfe5ab5f00277942d4d4200328b4d403c"
)


# RAZORPAY_KEY_ID = 'rzp_test_TQTiv6aVNjku4w'
# RAZORPAY_KEY_SECRET ='M6R5mKwPQ7mj2HsPP6ydASJn'
# RAZORPAY_WEBHOOK_SECRET="your_actual_webhook_secret"

RAZORPAY_KEY_ID = os.environ.get(
    "RAZORPAY_KEY_ID",
    ""
)

RAZORPAY_KEY_SECRET = os.environ.get(
    "RAZORPAY_KEY_SECRET",
    ""
)

RAZORPAY_WEBHOOK_SECRET = os.environ.get(
    "RAZORPAY_WEBHOOK_SECRET",
    ""
)


# telinfy whatsapp

# TELINFY_API_KEY = "ac8bba62-9bc2-11f1-af5a-a8a159c17b9a"

# TELINFY_BASE_URL = (
#     "https://hub.telinfy.com/unified/developer"
# )
# PUBLIC_BASE_URL = "https://flyingfoxadventuremunnar.com"

# TELINFY_WHATSAPP_TEMPLATE = "booking_confirmation_qr"

# TELINFY_WHATSAPP_LANGUAGE = "en"



TELINFY_API_KEY = os.environ.get(
    "TELINFY_API_KEY",
    ""
)

TELINFY_BASE_URL = os.environ.get(
    "TELINFY_BASE_URL",
    "https://hub.telinfy.com/unified/developer",
)

TELINFY_WHATSAPP_TEMPLATE = os.environ.get(
    "TELINFY_WHATSAPP_TEMPLATE",
    "booking_confirmation_qr",
)

TELINFY_WHATSAPP_LANGUAGE = os.environ.get(
    "TELINFY_WHATSAPP_LANGUAGE",
    "en",
)


TELINFY_SMS_API_URL = os.environ.get(
    "TELINFY_SMS_API_URL",
    "https://hub.telinfy.com/unified/developer/api/v1/sms/send",
)

TELINFY_SMS_SENDER_NAME = os.environ.get(
    "TELINFY_SMS_SENDER_NAME",
    "FLFXAD",
)

TELINFY_OTP_TEMPLATE_ID = os.environ.get(
    "TELINFY_OTP_TEMPLATE_ID",
    "",
)





# telinfy otp sms 
# TELINFY_SMS_API_URL = (
#     "https://hub.telinfy.com/"
#     "unified/developer/api/v1/sms/send"
# )

# TELINFY_SMS_SENDER_NAME = "FLFXAD"

# TELINFY_OTP_TEMPLATE_ID = "1777178816423927079"



# 
# TURNSTILE_SITE_KEY = "1x00000000000000000000AA"

# TURNSTILE_SECRET_KEY = "1x0000000000000000000000000000000AA"
TURNSTILE_SITE_KEY = os.environ.get(
    "TURNSTILE_SITE_KEY",
    ""
)

TURNSTILE_SECRET_KEY = os.environ.get(
    "TURNSTILE_SECRET_KEY",
    ""
)