# Generated by Django 5.2.16 on 2026-07-30 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='timeslot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='rideblackoutdate',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='rideimage',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='ridetimeslot',
            name='ride',
        ),
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='ride',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='maximum_age',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='maximum_weight',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='minimum_age',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='minimum_weight',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='short_description',
        ),
        migrations.AddField(
            model_name='ride',
            name='duration',
            field=models.CharField(default='30 Minutes', help_text='Example: 30 Minutes / 1 Hour', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='RideMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rides/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='rides/videos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='rides/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='flyingfox_app.ride')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='RideBlackoutDate',
        ),
        migrations.DeleteModel(
            name='RideImage',
        ),
        migrations.DeleteModel(
            name='RideTimeSlot',
        ),
    ]
