# Generated by Django 5.2.16 on 2026-07-30 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0005_remove_booking_coupon_remove_booking_timeslot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RidePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='flyingfox_app.ride')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
