# Generated by Django 5.2.16 on 2026-07-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0008_booking_discount_amount_coupon_booking_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='video_url',
        ),
    ]
