# Generated by Django 5.2.16 on 2026-07-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0011_alter_galleryitem_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
