# Generated by Django 5.2.16 on 2026-07-31 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0012_alter_galleryitem_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridemedia',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='ridemedia',
            name='video_url',
        ),
    ]
