# Generated by Django 5.2.16 on 2026-08-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0013_remove_ridemedia_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ridemedia',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='ride',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Enable this to show the ride in featured sections.'),
        ),
    ]
