# Generated by Django 5.2.16 on 2026-08-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0017_alter_booking_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='sms_sent',
        ),
        migrations.AddField(
            model_name='ticket',
            name='sms_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sms_status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
