# Generated by Django 5.2.16 on 2026-08-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0018_remove_ticket_sms_sent_ticket_sms_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
