# Generated by Django 5.2.16 on 2026-08-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0020_chatbotrule_chatsession_chatmessage_chatenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='onboarding_step',
            field=models.CharField(choices=[('name', 'Waiting For Name'), ('phone', 'Waiting For Phone'), ('email', 'Waiting For Email'), ('completed', 'Completed')], default='name', max_length=20),
        ),
    ]
