# Generated by Django 5.2.16 on 2026-08-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0021_chatsession_onboarding_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_at',
        ),
    ]
