# Generated by Django 5.2.16 on 2026-08-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0023_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('expired', 'Expired')], default='expired', editable=False, max_length=20),
        ),
    ]
