# Generated by Django 5.2.15 on 2026-08-15 08:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0033_remove_booking_adult_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='ride',
            name='age_limit',
            field=models.CharField(blank=True, help_text='Example: No Age Limit', max_length=100),
        ),
        migrations.AddField(
            model_name='ride',
            name='photography_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='photography_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='ride',
            name='videography_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='videography_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='ride',
            name='weight_limit',
            field=models.CharField(blank=True, help_text='Example: 15 - 120 KG', max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='duration',
            field=models.CharField(help_text='Example: 120 Seconds', max_length=100),
        ),
    ]
