# Generated by Django 5.2.15 on 2026-08-15 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0034_alter_ride_options_ride_age_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='ride',
            name='age_limit',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='photography_available',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='photography_price',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='videography_available',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='videography_price',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='weight_limit',
        ),
        migrations.AlterField(
            model_name='ride',
            name='duration',
            field=models.CharField(help_text='Example: 30 Minutes / 1 Hour', max_length=100),
        ),
        migrations.CreateModel(
            name='RideWeightRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.PositiveIntegerField()),
                ('max_weight', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_ranges', to='flyingfox_app.ride')),
            ],
            options={
                'ordering': ['sort_order', 'min_weight'],
            },
        ),
        migrations.CreateModel(
            name='BookingWeightGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('min_weight', models.PositiveIntegerField()),
                ('max_weight', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_groups', to='flyingfox_app.booking')),
                ('weight_range', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_weight_groups', to='flyingfox_app.rideweightrange')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('booking', 'weight_range'), name='unique_booking_weight_range')],
            },
        ),
    ]
