# Generated by Django 5.2.15 on 2026-08-15 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0035_alter_ride_options_remove_ride_age_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantWeightRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('min_weight', models.PositiveIntegerField()),
                ('max_weight', models.PositiveIntegerField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'min_weight'],
            },
        ),
        migrations.RemoveField(
            model_name='rideweightrange',
            name='ride',
        ),
        migrations.RemoveConstraint(
            model_name='bookingweightgroup',
            name='unique_booking_weight_range',
        ),
        migrations.RenameField(
            model_name='bookingweightgroup',
            old_name='quantity',
            new_name='participant_count',
        ),
        migrations.AddField(
            model_name='bookingweightgroup',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingweightgroup',
            name='weight_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_weight_groups', to='flyingfox_app.participantweightrange'),
        ),
        migrations.AddConstraint(
            model_name='bookingweightgroup',
            constraint=models.UniqueConstraint(fields=('booking', 'weight_range'), name='unique_booking_participant_weight_range'),
        ),
        migrations.DeleteModel(
            name='RideWeightRange',
        ),
    ]
