# Generated by Django 5.2.15 on 2026-08-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0036_participantweightrange_remove_rideweightrange_ride_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='addon_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='photo_addon',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='video_addon',
        ),
    ]
