# Generated by Django 5.2.15 on 2026-08-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0037_remove_booking_addon_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('verify_ticket', 'Can scan and verify tickets')]},
        ),
    ]
