# Generated by Django 5.2.15 on 2026-08-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0039_ticket_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
