# Generated by Django 5.2.15 on 2026-08-19 04:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0041_remove_bookingweightgroup_weight_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduction_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('admin_note', models.TextField(blank=True, default='')),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('razorpay_refund_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('gateway_status', models.CharField(blank=True, default='', max_length=50)),
                ('arn', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('processing', 'Processing'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='flyingfox_app.booking')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='flyingfox_app.payment')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
