# Generated by Django 5.2.15 on 2026-08-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0042_refund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingPerson',
        ),
    ]
