# Generated by Django 5.2.15 on 2026-08-20 08:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0044_alter_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_coupon_code', models.CharField(blank=True, default='', max_length=50)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='bookingweightgroup',
            name='unique_booking_weight_range',
        ),
        migrations.AlterField(
            model_name='bookingweightgroup',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_groups', to='flyingfox_app.booking'),
        ),
        migrations.AddField(
            model_name='bookingrideitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_items', to='flyingfox_app.booking'),
        ),
        migrations.AddField(
            model_name='bookingrideitem',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_items', to='flyingfox_app.offer'),
        ),
        migrations.AddField(
            model_name='bookingrideitem',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='flyingfox_app.ride'),
        ),
        migrations.AddField(
            model_name='bookingrideitem',
            name='ride_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='flyingfox_app.rideprice'),
        ),
        migrations.AddField(
            model_name='bookingweightgroup',
            name='booking_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_groups', to='flyingfox_app.bookingrideitem'),
        ),
        migrations.AddConstraint(
            model_name='bookingrideitem',
            constraint=models.UniqueConstraint(fields=('booking', 'ride'), name='unique_ride_per_booking'),
        ),
    ]
