# Generated by Django 5.2.15 on 2026-08-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0046_copy_existing_booking_rides'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookingweightgroup',
            constraint=models.UniqueConstraint(fields=('booking_item', 'range_key'), name='unique_booking_item_weight_range'),
        ),
    ]
