# Generated by Django 5.2.15 on 2026-08-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0047_bookingweightgroup_unique_booking_item_weight_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='ride',
        ),
        migrations.AddField(
            model_name='offer',
            name='rides',
            field=models.ManyToManyField(blank=True, related_name='offers', to='flyingfox_app.ride'),
        ),
    ]
