# Generated by Django 5.2.15 on 2026-08-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0049_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='phone',
            field=models.CharField(db_index=True, default=797, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otpverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
