# Generated by Django 5.2.15 on 2026-08-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0050_otpverification_phone_otpverification_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='whatsapp_ticket_image',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/whatsapp/'),
        ),
    ]
