# Generated by Django 5.2.15 on 2026-08-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0051_ticket_whatsapp_ticket_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='phone',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['phone_number', 'is_verified'], name='otp_phone_verified_idx'),
        ),
    ]
