# Generated by Django 5.2.15 on 2026-09-01 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyingfox_app', '0052_remove_otpverification_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='capacity_per_slot',
            field=models.PositiveIntegerField(default=15, help_text='Maximum number of participants allowed in one time slot for this ride.'),
        ),
        migrations.AddField(
            model_name='ride',
            name='slot_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration of one booking slot in minutes.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='BookingRideSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_start_time', models.TimeField()),
                ('slot_end_time', models.TimeField()),
                ('participant_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('held', 'Held'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='held', max_length=20)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_slots', to='flyingfox_app.bookingrideitem')),
            ],
            options={
                'ordering': ['slot_start_time'],
                'indexes': [models.Index(fields=['slot_start_time', 'status'], name='booking_slot_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking_item', 'slot_start_time'), name='unique_booking_item_start_slot'), models.CheckConstraint(condition=models.Q(('participant_count__gt', 0)), name='booking_ride_slot_participants_gt_0')],
            },
        ),
    ]
